/**
 * Portfolio Knowledge Base
 * 
 * This file aggregates all portfolio data into a structured knowledge base
 * that the AI assistant uses to answer questions. It is automatically
 * regenerated whenever portfolio data changes (via admin panel or data updates).
 * 
 * DO NOT edit this file manually — it is generated from:
 * - Site settings (profile, education, social links)
 * - Projects (with full descriptions, technologies, architecture)
 * - Experience & Education
 * - Skills & Certifications
 * - Achievements
 * - Live platform stats (GitHub, LeetCode, CodeChef)
 */

import { 
  Project, Note, Experience, LearningTopic, 
  Achievement, Certification, EducationItem, Skill, SiteSettings 
} from '@/types';

// ============================================================================
// KNOWLEDGE BASE INTERFACES
// ============================================================================

export interface KnowledgeProfile {
  name: string;
  role: string;
  bio: string;
  currentStatus: string;
  university: string;
  degree: string;
  year: string;
  cgpa: {
    overall: string;
    sem1: string;
    sem2: string;
  };
  email: string;
  links: {
    github: string;
    linkedin: string;
    leetcode: string;
    codechef: string;
    resume: string;
  };
}

export interface KnowledgeProject {
  id: string;
  title: string;
  category: string;
  status: string;
  featured: boolean;
  shortDescription: string;
  fullDescription: string;
  technologies: string[];
  liveUrl?: string;
  githubUrl?: string;
  features: string[];
  problem?: string;
  solution?: string;
  architecture?: string;
}

export interface KnowledgeExperience {
  title: string;
  company: string;
  duration: string;
  location?: string;
  description?: string;
  technologies?: string[];
}

export interface KnowledgeEducation {
  degree: string;
  institution: string;
  year?: string;
  cgpa?: string;
  description?: string;
}

export interface KnowledgeSkill {
  name: string;
  category: string;
  level?: number;
}

export interface KnowledgeCertification {
  title: string;
  issuer?: string;
  date?: string;
  description?: string;
}

export interface KnowledgeAchievement {
  title: string;
  description?: string;
  date?: string;
}

export interface KnowledgeStats {
  github?: {
    stars: number;
    followers: number;
    repos: number;
    commits: number;
    topLanguages: string[];
  };
  leetcode?: {
    solved: number;
    rating: number;
    globalRank: number;
    easy: number;
    medium: number;
    hard: number;
    contests: number;
  };
  codechef?: {
    rating: number;
    stars: string;
    globalRank: number;
    solved: number;
  };
}

export interface PortfolioKnowledgeBase {
  profile: KnowledgeProfile;
  projects: KnowledgeProject[];
  experience: KnowledgeExperience[];
  education: KnowledgeEducation[];
  skills: KnowledgeSkill[];
  certifications: KnowledgeCertification[];
  achievements: KnowledgeAchievement[];
  stats: KnowledgeStats;
  lastUpdated: string;
  dataVersion: number;
}

// ============================================================================
// KNOWLEDGE BASE BUILDER
// ============================================================================

/**
 * Build the complete knowledge base from all portfolio data.
 * Call this whenever data changes to refresh the AI's knowledge.
 */
export function buildKnowledgeBase(data: {
  settings: SiteSettings;
  projects: Project[];
  notes: Note[];
  experience: Experience[];
  learning: LearningTopic[];
  achievements: Achievement[];
  certifications: Certification[];
  education: EducationItem[];
  skills: Skill[];
  stats?: any;
}): PortfolioKnowledgeBase {
  return {
    profile: buildProfile(data.settings),
    projects: buildProjects(data.projects),
    experience: buildExperience(data.experience),
    education: buildEducation(data.education, data.settings),
    skills: buildSkills(data.skills),
    certifications: buildCertifications(data.certifications),
    achievements: buildAchievements(data.achievements),
    stats: buildStats(data.stats),
    lastUpdated: new Date().toISOString(),
    dataVersion: Date.now(),
  };
}

function buildProfile(s: SiteSettings): KnowledgeProfile {
  return {
    name: s.name,
    role: s.role,
    bio: s.bio,
    currentStatus: s.currentStatus,
    university: s.university,
    degree: s.degree,
    year: s.year,
    cgpa: {
      overall: s.cgpaOverall,
      sem1: s.cgpaFirstSem,
      sem2: s.cgpaSecondSem,
    },
    email: s.email,
    links: {
      github: s.github,
      linkedin: s.linkedin,
      leetcode: s.leetcode || '',
      codechef: s.codechef || '',
      resume: s.resumeUrl,
    },
  };
}

function buildProjects(projects: Project[]): KnowledgeProject[] {
  return projects
    .filter(p => p.published !== false)
    .map(p => ({
      id: p.id,
      title: p.title,
      category: p.category,
      status: p.status,
      featured: p.featured,
      shortDescription: p.shortDescription,
      fullDescription: p.fullDescription || p.shortDescription,
      technologies: p.technologies || [],
      liveUrl: p.liveDemoUrl,
      githubUrl: p.githubUrl,
      features: p.features || [],
      problem: p.problem,
      solution: p.solution,
      architecture: p.architectureDescription,
    }));
}

function buildExperience(exp: Experience[]): KnowledgeExperience[] {
  return exp.map(e => ({
    title: e.title,
    company: e.company,
    duration: e.duration,
    location: e.location,
    description: e.description,
    technologies: e.technologies,
  }));
}

function buildEducation(edu: EducationItem[], s: SiteSettings): KnowledgeEducation[] {
  const items: KnowledgeEducation[] = edu.map(e => ({
    degree: e.degree || e.institution,
    institution: e.institution || e.degree,
    year: e.year,
    cgpa: e.cgpa,
    description: e.description,
  }));
  
  // Always include primary education from settings
  if (!items.some(i => i.institution === s.university)) {
    items.unshift({
      degree: s.degree,
      institution: s.university,
      year: s.year,
      cgpa: s.cgpaOverall,
    });
  }
  
  return items;
}

function buildSkills(skills: Skill[]): KnowledgeSkill[] {
  return skills.map(s => ({
    name: s.name,
    category: s.category || 'Other',
    level: s.level,
  }));
}

function buildCertifications(certs: Certification[]): KnowledgeCertification[] {
  return certs.map(c => ({
    title: c.title,
    issuer: c.issuer,
    date: c.date,
    description: c.description,
  }));
}

function buildAchievements(achs: Achievement[]): KnowledgeAchievement[] {
  return achs.map(a => ({
    title: a.title,
    description: a.description,
    date: a.date,
  }));
}

function buildStats(stats: any): KnowledgeStats {
  if (!stats) return {};
  
  const result: KnowledgeStats = {};
  
  if (stats.github && !('error' in stats.github)) {
    result.github = {
      stars: stats.github.totalStars || 0,
      followers: stats.github.followers || 0,
      repos: stats.github.publicRepos || 0,
      commits: stats.github.totalCommits || 0,
      topLanguages: stats.github.topLanguages?.map((l: any) => l.language) || [],
    };
  }
  
  if (stats.leetcode && !('error' in stats.leetcode)) {
    result.leetcode = {
      solved: stats.leetcode.totalSolved || 0,
      rating: stats.leetcode.contestRating || 0,
      globalRank: stats.leetcode.globalRanking || 0,
      easy: stats.leetcode.acEasy || 0,
      medium: stats.leetcode.acMedium || 0,
      hard: stats.leetcode.acHard || 0,
      contests: stats.leetcode.contestNum || 0,
    };
  }
  
  if (stats.codechef && !('error' in stats.codechef)) {
    result.codechef = {
      rating: stats.codechef.rating || 0,
      stars: stats.codechef.stars || '',
      globalRank: stats.codechef.globalRank || 0,
      solved: stats.codechef.problemsSolved || 0,
    };
  }
  
  return result;
}

// ============================================================================
// KNOWLEDGE BASE SERIALIZATION (for AI context)
// ============================================================================

/**
 * Serialize the knowledge base into a text format suitable for AI context.
 * This creates a comprehensive text representation of all portfolio data.
 */
export function serializeKnowledgeBase(kb: PortfolioKnowledgeBase): string {
  const lines: string[] = [];
  
  // Profile
  lines.push('=== PROFILE ===');
  lines.push(`Name: ${kb.profile.name}`);
  lines.push(`Role: ${kb.profile.role}`);
  lines.push(`Status: ${kb.profile.currentStatus}`);
  lines.push(`Bio: ${kb.profile.bio}`);
  lines.push(`University: ${kb.profile.university}`);
  lines.push(`Degree: ${kb.profile.degree}`);
  lines.push(`Year: ${kb.profile.year}`);
  lines.push(`CGPA: ${kb.profile.cgpa.overall}/10.0 (Sem 1: ${kb.profile.cgpa.sem1}, Sem 2: ${kb.profile.cgpa.sem2})`);
  lines.push(`Email: ${kb.profile.email}`);
  lines.push(`GitHub: ${kb.profile.links.github}`);
  lines.push(`LinkedIn: ${kb.profile.links.linkedin}`);
  lines.push(`LeetCode: ${kb.profile.links.leetcode}`);
  lines.push(`CodeChef: ${kb.profile.links.codechef}`);
  lines.push(`Resume: ${kb.profile.links.resume}`);
  
  // Projects
  lines.push('');
  lines.push('=== PROJECTS ===');
  kb.projects.forEach(p => {
    lines.push('');
    lines.push(`[${p.id}] ${p.title}`);
    lines.push(`  Category: ${p.category} | Status: ${p.status} | Featured: ${p.featured ? 'Yes' : 'No'}`);
    lines.push(`  Description: ${p.shortDescription}`);
    if (p.fullDescription !== p.shortDescription) {
      lines.push(`  Full Description: ${p.fullDescription}`);
    }
    lines.push(`  Technologies: ${p.technologies.join(', ')}`);
    if (p.liveUrl) lines.push(`  Live Demo: ${p.liveUrl}`);
    if (p.githubUrl) lines.push(`  GitHub: ${p.githubUrl}`);
    if (p.problem) lines.push(`  Problem: ${p.problem}`);
    if (p.solution) lines.push(`  Solution: ${p.solution}`);
    if (p.architecture) lines.push(`  Architecture: ${p.architecture}`);
    if (p.features.length > 0) {
      lines.push(`  Features:`);
      p.features.forEach(f => lines.push(`    - ${f}`));
    }
  });
  
  // Experience
  if (kb.experience.length > 0) {
    lines.push('');
    lines.push('=== EXPERIENCE ===');
    kb.experience.forEach(e => {
      lines.push(`  ${e.title} at ${e.company} (${e.duration})`);
      if (e.location) lines.push(`    Location: ${e.location}`);
      if (e.description) lines.push(`    ${e.description}`);
      if (e.technologies) lines.push(`    Technologies: ${e.technologies.join(', ')}`);
    });
  }
  
  // Education
  lines.push('');
  lines.push('=== EDUCATION ===');
  kb.education.forEach(e => {
    lines.push(`  ${e.degree} — ${e.institution} ${e.year ? `(${e.year})` : ''}`);
    if (e.cgpa) lines.push(`    CGPA: ${e.cgpa}`);
    if (e.description) lines.push(`    ${e.description}`);
  });
  
  // Skills
  if (kb.skills.length > 0) {
    lines.push('');
    lines.push('=== SKILLS ===');
    const skillByCategory = new Map<string, string[]>();
    kb.skills.forEach(s => {
      if (!skillByCategory.has(s.category)) skillByCategory.set(s.category, []);
      skillByCategory.get(s.category)!.push(s.name);
    });
    skillByCategory.forEach((skills, cat) => {
      lines.push(`  ${cat}: ${skills.join(', ')}`);
    });
  }
  
  // Certifications
  if (kb.certifications.length > 0) {
    lines.push('');
    lines.push('=== CERTIFICATIONS ===');
    kb.certifications.forEach(c => {
      lines.push(`  ${c.title}${c.issuer ? ` — ${c.issuer}` : ''}${c.date ? ` (${c.date})` : ''}`);
      if (c.description) lines.push(`    ${c.description}`);
    });
  }
  
  // Achievements
  if (kb.achievements.length > 0) {
    lines.push('');
    lines.push('=== ACHIEVEMENTS ===');
    kb.achievements.forEach(a => {
      lines.push(`  ${a.title}${a.date ? ` (${a.date})` : ''}`);
      if (a.description) lines.push(`    ${a.description}`);
    });
  }
  
  // Live Stats
  lines.push('');
  lines.push('=== LIVE CODING STATS ===');
  if (kb.stats.github) {
    const g = kb.stats.github;
    lines.push(`GitHub: ${g.stars} stars, ${g.followers} followers, ${g.repos} repos, ${g.commits} recent commits`);
    if (g.topLanguages.length > 0) lines.push(`  Top Languages: ${g.topLanguages.join(', ')}`);
  }
  if (kb.stats.leetcode) {
    const l = kb.stats.leetcode;
    lines.push(`LeetCode: ${l.solved} problems solved, Rating ${l.rating}, Global Rank #${l.globalRank}, ${l.contests} contests`);
    lines.push(`  Easy: ${l.easy}, Medium: ${l.medium}, Hard: ${l.hard}`);
  }
  if (kb.stats.codechef) {
    const c = kb.stats.codechef;
    lines.push(`CodeChef: Rating ${c.rating}, ${c.stars} stars, Global Rank #${c.globalRank}, ${c.solved} problems solved`);
  }
  
  lines.push('');
  lines.push(`Last updated: ${kb.lastUpdated}`);
  
  return lines.join('\n');
}

// ============================================================================
// RETRIEVAL FUNCTIONS (for targeted AI context)
// ============================================================================

/**
 * Retrieve relevant portfolio data based on a user query.
 * Returns a focused subset of the knowledge base.
 */
export function retrieveRelevantData(kb: PortfolioKnowledgeBase, query: string): string {
  const lower = query.toLowerCase();
  const results: string[] = [];
  
  // Profile queries
  if (matchesAny(lower, ['who', 'about', 'intro', 'profile', 'name', 'background'])) {
    results.push(`Profile: ${kb.profile.name} — ${kb.profile.role}. ${kb.profile.bio}`);
    results.push(`Status: ${kb.profile.currentStatus}`);
  }
  
  // CGPA / Education queries
  if (matchesAny(lower, ['cgpa', 'academic', 'gpa', 'grade', 'semester', 'education', 'university', 'college', 'degree'])) {
    results.push(`Education: ${kb.profile.degree}, ${kb.profile.year} at ${kb.profile.university}`);
    results.push(`CGPA: ${kb.profile.cgpa.overall}/10.0 (Sem 1: ${kb.profile.cgpa.sem1}, Sem 2: ${kb.profile.cgpa.sem2})`);
    kb.education.forEach(e => {
      results.push(`  ${e.degree} — ${e.institution} ${e.year ? `(${e.year})` : ''} ${e.cgpa ? `CGPA: ${e.cgpa}` : ''}`);
    });
  }
  
  // Project queries
  if (matchesAny(lower, ['project', 'build', 'system', 'made', 'portfolio', 'work'])) {
    // Check for specific project mention
    const specificProject = kb.projects.find(p => 
      lower.includes(p.title.toLowerCase()) || 
      p.technologies.some(t => lower.includes(t.toLowerCase()))
    );
    
    if (specificProject) {
      const p = specificProject;
      results.push(`Project: ${p.title} (${p.category}, ${p.status})`);
      results.push(`Description: ${p.fullDescription}`);
      results.push(`Technologies: ${p.technologies.join(', ')}`);
      if (p.problem) results.push(`Problem: ${p.problem}`);
      if (p.solution) results.push(`Solution: ${p.solution}`);
      if (p.architecture) results.push(`Architecture: ${p.architecture}`);
      if (p.features.length > 0) results.push(`Features: ${p.features.join('; ')}`);
      if (p.liveUrl) results.push(`Live Demo: ${p.liveUrl}`);
      if (p.githubUrl) results.push(`GitHub: ${p.githubUrl}`);
    } else {
      // List all projects
      results.push(`Projects (${kb.projects.length} total):`);
      kb.projects.forEach(p => {
        results.push(`  • ${p.title} (${p.category}): ${p.shortDescription}`);
        results.push(`    Tech: ${p.technologies.join(', ')}`);
      });
    }
  }
  
  // Tech / Skills queries
  if (matchesAny(lower, ['tech', 'skill', 'technology', 'know', 'language', 'framework', 'stack'])) {
    const skillByCategory = new Map<string, string[]>();
    kb.skills.forEach(s => {
      if (!skillByCategory.has(s.category)) skillByCategory.set(s.category, []);
      skillByCategory.get(s.category)!.push(s.name);
    });
    results.push('Skills:');
    skillByCategory.forEach((skills, cat) => {
      results.push(`  ${cat}: ${skills.join(', ')}`);
    });
    
    // Also list technologies from projects
    const projectTechs = Array.from(new Set(kb.projects.flatMap(p => p.technologies)));
    results.push(`Project Technologies: ${projectTechs.join(', ')}`);
  }
  
  // Experience queries
  if (matchesAny(lower, ['experience', 'work', 'job', 'internship', 'career'])) {
    if (kb.experience.length > 0) {
      results.push('Experience:');
      kb.experience.forEach(e => {
        results.push(`  • ${e.title} at ${e.company} (${e.duration})`);
        if (e.description) results.push(`    ${e.description}`);
      });
    } else {
      results.push('Experience: No formal work experience listed. Focus on projects and academics.');
    }
  }
  
  // GitHub queries
  if (matchesAny(lower, ['github', 'git', 'repos', 'repository', 'commit'])) {
    results.push(`GitHub: ${kb.profile.links.github}`);
    if (kb.stats.github) {
      const g = kb.stats.github;
      results.push(`Stats: ${g.stars} stars, ${g.followers} followers, ${g.repos} repos, ${g.commits} recent commits`);
      if (g.topLanguages.length > 0) results.push(`Top Languages: ${g.topLanguages.join(', ')}`);
    }
  }
  
  // LeetCode queries
  if (matchesAny(lower, ['leetcode', 'problem', 'solved', 'competitive'])) {
    results.push(`LeetCode: ${kb.profile.links.leetcode}`);
    if (kb.stats.leetcode) {
      const l = kb.stats.leetcode;
      results.push(`Stats: ${l.solved} problems solved, Rating ${l.rating}, Global Rank #${l.globalRank}, ${l.contests} contests`);
      results.push(`Breakdown: Easy ${l.easy}, Medium ${l.medium}, Hard ${l.hard}`);
    }
  }
  
  // CodeChef queries
  if (matchesAny(lower, ['codechef', 'contest', 'rating'])) {
    results.push(`CodeChef: ${kb.profile.links.codechef}`);
    if (kb.stats.codechef) {
      const c = kb.stats.codechef;
      results.push(`Stats: Rating ${c.rating}, ${c.stars} stars, Global Rank #${c.globalRank}, ${c.solved} problems solved`);
    }
  }
  
  // Stats queries (general)
  if (matchesAny(lower, ['stat', 'coding stat', 'activity', 'analytics'])) {
    results.push('=== LIVE CODING STATS ===');
    if (kb.stats.github) {
      const g = kb.stats.github;
      results.push(`GitHub: ${g.stars}★, ${g.followers}👥, ${g.repos} repos, ${g.commits} commits`);
    }
    if (kb.stats.leetcode) {
      const l = kb.stats.leetcode;
      results.push(`LeetCode: ${l.solved} solved, Rating ${l.rating}, Rank #${l.globalRank}`);
    }
    if (kb.stats.codechef) {
      const c = kb.stats.codechef;
      results.push(`CodeChef: Rating ${c.rating}, Rank #${c.globalRank}`);
    }
    if (!kb.stats.github && !kb.stats.leetcode && !kb.stats.codechef) {
      results.push('Stats are currently loading or unavailable.');
    }
  }
  
  // Contact queries
  if (matchesAny(lower, ['contact', 'email', 'reach', 'connect', 'whatsapp', 'message', 'linkedin'])) {
    results.push('Contact Information:');
    results.push(`  Email: ${kb.profile.email}`);
    results.push(`  GitHub: ${kb.profile.links.github}`);
    results.push(`  LinkedIn: ${kb.profile.links.linkedin}`);
    results.push(`  LeetCode: ${kb.profile.links.leetcode}`);
    results.push(`  CodeChef: ${kb.profile.links.codechef}`);
    if (kb.profile.links.resume && kb.profile.links.resume !== '#') {
      results.push(`  Resume: ${kb.profile.links.resume}`);
    }
  }
  
  // Certifications
  if (matchesAny(lower, ['certif', 'certificate', 'course'])) {
    if (kb.certifications.length > 0) {
      results.push('Certifications:');
      kb.certifications.forEach(c => {
        results.push(`  • ${c.title}${c.issuer ? ` — ${c.issuer}` : ''}${c.date ? ` (${c.date})` : ''}`);
      });
    } else {
      results.push('No certifications listed.');
    }
  }
  
  // Achievements
  if (matchesAny(lower, ['achievement', 'award', 'honor'])) {
    if (kb.achievements.length > 0) {
      results.push('Achievements:');
      kb.achievements.forEach(a => {
        results.push(`  • ${a.title}${a.date ? ` (${a.date})` : ''}`);
        if (a.description) results.push(`    ${a.description}`);
      });
    } else {
      results.push('No achievements listed.');
    }
  }
  
  // If nothing matched, return full knowledge base
  if (results.length === 0) {
    return serializeKnowledgeBase(kb);
  }
  
  return results.join('\n');
}

function matchesAny(text: string, keywords: string[]): boolean {
  return keywords.some(kw => text.includes(kw));
}
