/**
 * Portfolio Knowledge Base
 * 
 * This file aggregates all portfolio data into a structured knowledge base
 * that the AI assistant uses to answer questions. It is automatically
 * regenerated whenever portfolio data changes (via admin panel or data updates).
 * 
 * DO NOT edit this file manually — it is generated from:
 * - Site settings (profile, education, social links)
 * - Projects (with full descriptions, technologies, architecture)
 * - Experience & Education
 * - Skills & Certifications
 * - Achievements
 * - Live platform stats (GitHub, LeetCode, CodeChef)
 */

import { 
  Project, Note, Experience, LearningTopic, 
  Achievement, Certification, EducationItem, Skill, SiteSettings 
} from '@/types';

// ============================================================================
// KNOWLEDGE BASE INTERFACES
// ============================================================================

export interface KnowledgeProfile {
  name: string;
  role: string;
  bio: string;
  currentStatus: string;
  university: string;
  degree: string;
  year: string;
  cgpa: {
    overall: string;
    sem1: string;
    sem2: string;
  };
  email: string;
  links: {
    github: string;
    linkedin: string;
    leetcode: string;
    codechef: string;
    resume: string;
  };
}

export interface KnowledgeProject {
  id: string;
  title: string;
  category: string;
  status: string;
  featured: boolean;
  shortDescription: string;
  fullDescription: string;
  technologies: string[];
  liveUrl?: string;
  githubUrl?: string;
  features: string[];
  problem?: string;
  solution?: string;
  architecture?: string;
}

export interface KnowledgeExperience {
  title: string;
  company: string;
  duration: string;
  location?: string;
  description?: string;
  technologies?: string[];
}

export interface KnowledgeEducation {
  degree: string;
  institution: string;
  year?: string;
  cgpa?: string;
  description?: string;
}

export interface KnowledgeSkill {
  name: string;
  category: string;
  level?: number;
}

export interface KnowledgeCertification {
  title: string;
  issuer?: string;
  date?: string;
  description?: string;
}

export interface KnowledgeAchievement {
  title: string;
  description?: string;
  date?: string;
}

export interface KnowledgeStats {
  github?: {
    stars: number;
    followers: number;
    repos: number;
    commits: number;
    topLanguages: string[];
  };
  leetcode?: {
    solved: number;
    rating: number;
    globalRank: number;
    easy: number;
    medium: number;
    hard: number;
    contests: number;
  };
  codechef?: {
    rating: number;
    stars: string;
    globalRank: number;
    solved: number;
  };
}

export interface PortfolioKnowledgeBase {
  profile: KnowledgeProfile;
  projects: KnowledgeProject[];
  experience: KnowledgeExperience[];
  education: KnowledgeEducation[];
  skills: KnowledgeSkill[];
  certifications: KnowledgeCertification[];
  achievements: KnowledgeAchievement[];
  stats: KnowledgeStats;
  lastUpdated: string;
  dataVersion: number;
}

// ============================================================================
// KNOWLEDGE BASE BUILDER
// ============================================================================

/**
 * Build the complete knowledge base from all portfolio data.
 * Call this whenever data changes to refresh the AI's knowledge.
 */
export function buildKnowledgeBase(data: {
  settings: SiteSettings;
  projects: Project[];
  notes: Note[];
  experience: Experience[];
  learning: LearningTopic[];
  achievements: Achievement[];
  certifications: Certification[];
  education: EducationItem[];
  skills: Skill[];
  stats?: any;
}): PortfolioKnowledgeBase {
  return {
    profile: buildProfile(data.settings),
    projects: buildProjects(data.projects),
    experience: buildExperience(data.experience),
    education: buildEducation(data.education, data.settings),
    skills: buildSkills(data.skills),
    certifications: buildCertifications(data.certifications),
    achievements: buildAchievements(data.achievements),
    stats: buildStats(data.stats),
    lastUpdated: new Date().toISOString(),
    dataVersion: Date.now(),
  };
}

function buildProfile(s: SiteSettings): KnowledgeProfile {
  return {
    name: s.name,
    role: s.role,
    bio: s.bio,
    currentStatus: s.currentStatus,
    university: s.university,
    degree: s.degree,
    year: s.year,
    cgpa: {
      overall: s.cgpaOverall,
      sem1: s.cgpaFirstSem,
      sem2: s.cgpaSecondSem,
    },
    email: s.email,
    links: {
      github: s.github,
      linkedin: s.linkedin,
      leetcode: s.leetcode || '',
      codechef: s.codechef || '',
      resume: s.resumeUrl,
    },
  };
}

function buildProjects(projects: Project[]): KnowledgeProject[] {
  return projects
    .filter(p => p.published !== false)
    .map(p => ({
      id: p.id,
      title: p.title,
      category: p.category,
      status: p.status,
      featured: p.featured,
      shortDescription: p.shortDescription,
      fullDescription: p.fullDescription || p.shortDescription,
      technologies: p.technologies || [],
      liveUrl: p.liveDemoUrl,
      githubUrl: p.githubUrl,
      features: p.features || [],
      problem: p.problem,
      solution: p.solution,
      architecture: p.architectureDescription,
    }));
}

function buildExperience(exp: Experience[]): KnowledgeExperience[] {
  return exp.map(e => ({
    title: e.role,
    company: e.organization,
    duration: `${e.startDate}${e.endDate ? ` - ${e.endDate}` : ''}`,
    location: e.location,
    description: e.description,
    technologies: e.technologies,
  }));
}

function buildEducation(edu: EducationItem[], s: SiteSettings): KnowledgeEducation[] {
  const items: KnowledgeEducation[] = edu.map(e => ({
    degree: e.degree || e.institution,
    institution: e.institution || e.degree,
    year: e.year,
    cgpa: e.cgpa,
    description: e.description,
  }));
  
  // Always include primary education from settings
  if (!items.some(i => i.institution === s.university)) {
    items.unshift({
      degree: s.degree,
      institution: s.university,
      year: s.year,
      cgpa: s.cgpaOverall,
    });
  }
  
  return items;
}

function buildSkills(skills: Skill[]): KnowledgeSkill[] {
  return skills.map(s => ({
    name: s.name,
    category: s.group,
  }));
}

function buildCertifications(certs: Certification[]): KnowledgeCertification[] {
  return certs.map(c => ({
    title: c.title,
    issuer: c.issuer,
    date: c.date,
    description: c.description,
  }));
}

function buildAchievements(achs: Achievement[]): KnowledgeAchievement[] {
  return achs.map(a => ({
    title: a.title,
    description: a.description,
    date: a.date,
  }));
}

function buildStats(stats: any): KnowledgeStats {
  if (!stats) return {};
  
  const result: KnowledgeStats = {};
  
  if (stats.github && !('error' in stats.github)) {
    result.github = {
      stars: stats.github.totalStars || 0,
      followers: stats.github.followers || 0,
      repos: stats.github.publicRepos || 0,
      commits: stats.github.totalCommits || 0,
      topLanguages: stats.github.topLanguages?.map((l: any) => l.language) || [],
    };
  }
  
  if (stats.leetcode && !('error' in stats.leetcode)) {
    result.leetcode = {
      solved: stats.leetcode.totalSolved || 0,
      rating: stats.leetcode.contestRating || 0,
      globalRank: stats.leetcode.globalRanking || 0,
      easy: stats.leetcode.acEasy || 0,
      medium: stats.leetcode.acMedium || 0,
      hard: stats.leetcode.acHard || 0,
      contests: stats.leetcode.contestNum || 0,
    };
  }
  
  if (stats.codechef && !('error' in stats.codechef)) {
    result.codechef = {
      rating: stats.codechef.rating || 0,
      stars: stats.codechef.stars || '',
      globalRank: stats.codechef.globalRank || 0,
      solved: stats.codechef.problemsSolved || 0,
    };
  }
  
  return result;
}

// ============================================================================
// KNOWLEDGE BASE SERIALIZATION (for AI context)
// ============================================================================

/**
 * Serialize the knowledge base into a text format suitable for AI context.
 * This creates a comprehensive text representation of all portfolio data.
 */
export function serializeKnowledgeBase(kb: PortfolioKnowledgeBase): string {
  const lines: string[] = [];
  
  // Profile
  lines.push('=== PROFILE ===');
  lines.push(`Name: ${kb.profile.name}`);
  lines.push(`Role: ${kb.profile.role}`);
  lines.push(`Status: ${kb.profile.currentStatus}`);
  lines.push(`Bio: ${kb.profile.bio}`);
  lines.push(`University: ${kb.profile.university}`);
  lines.push(`Degree: ${kb.profile.degree}`);
  lines.push(`Year: ${kb.profile.year}`);
  lines.push(`CGPA: ${kb.profile.cgpa.overall}/10.0 (Sem 1: ${kb.profile.cgpa.sem1}, Sem 2: ${kb.profile.cgpa.sem2})`);
  lines.push(`Email: ${kb.profile.email}`);
  lines.push(`GitHub: ${kb.profile.links.github}`);
  lines.push(`LinkedIn: ${kb.profile.links.linkedin}`);
  lines.push(`LeetCode: ${kb.profile.links.leetcode}`);
  lines.push(`CodeChef: ${kb.profile.links.codechef}`);
  lines.push(`Resume: ${kb.profile.links.resume}`);
  
  // Projects
  lines.push('');
  lines.push('=== PROJECTS ===');
  kb.projects.forEach(p => {
    lines.push('');
    lines.push(`[${p.id}] ${p.title}`);
    lines.push(`  Category: ${p.category} | Status: ${p.status} | Featured: ${p.featured ? 'Yes' : 'No'}`);
    lines.push(`  Description: ${p.shortDescription}`);
    if (p.fullDescription !== p.shortDescription) {
      lines.push(`  Full Description: ${p.fullDescription}`);
    }
    lines.push(`  Technologies: ${p.technologies.join(', ')}`);
    if (p.liveUrl) lines.push(`  Live Demo: ${p.liveUrl}`);
    if (p.githubUrl) lines.push(`  GitHub: ${p.githubUrl}`);
    if (p.problem) lines.push(`  Problem: ${p.problem}`);
    if (p.solution) lines.push(`  Solution: ${p.solution}`);
    if (p.architecture) lines.push(`  Architecture: ${p.architecture}`);
    if (p.features.length > 0) {
      lines.push(`  Features:`);
      p.features.forEach(f => lines.push(`    - ${f}`));
    }
  });
  
  // Experience
  if (kb.experience.length > 0) {
    lines.push('');
    lines.push('=== EXPERIENCE ===');
    kb.experience.forEach(e => {
      lines.push(`  ${e.title} at ${e.company} (${e.duration})`);
      if (e.location) lines.push(`    Location: ${e.location}`);
      if (e.description) lines.push(`    ${e.description}`);
      if (e.technologies) lines.push(`    Technologies: ${e.technologies.join(', ')}`);
    });
  }
  
  // Education
  lines.push('');
  lines.push('=== EDUCATION ===');
  kb.education.forEach(e => {
    lines.push(`  ${e.degree} — ${e.institution} ${e.year ? `(${e.year})` : ''}`);
    if (e.cgpa) lines.push(`    CGPA: ${e.cgpa}`);
    if (e.description) lines.push(`    ${e.description}`);
  });
  
  // Skills
  if (kb.skills.length > 0) {
    lines.push('');
    lines.push('=== SKILLS ===');
    const skillByCategory = new Map<string, string[]>();
    kb.skills.forEach(s => {
      if (!skillByCategory.has(s.category)) skillByCategory.set(s.category, []);
      skillByCategory.get(s.category)!.push(s.name);
    });
    skillByCategory.forEach((skills, cat) => {
      lines.push(`  ${cat}: ${skills.join(', ')}`);
    });
  }
  
  // Certifications
  if (kb.certifications.length > 0) {
    lines.push('');
    lines.push('=== CERTIFICATIONS ===');
    kb.certifications.forEach(c => {
      lines.push(`  ${c.title}${c.issuer ? ` — ${c.issuer}` : ''}${c.date ? ` (${c.date})` : ''}`);
      if (c.description) lines.push(`    ${c.description}`);
    });
  }
  
  // Achievements
  if (kb.achievements.length > 0) {
    lines.push('');
    lines.push('=== ACHIEVEMENTS ===');
    kb.achievements.forEach(a => {
      lines.push(`  ${a.title}${a.date ? ` (${a.date})` : ''}`);
      if (a.description) lines.push(`    ${a.description}`);
    });
  }
  
  // Live Stats
  lines.push('');
  lines.push('=== LIVE CODING STATS ===');
  if (kb.stats.github) {
    const g = kb.stats.github;
    lines.push(`GitHub: ${g.stars} stars, ${g.followers} followers, ${g.repos} repos, ${g.commits} recent commits`);
    if (g.topLanguages.length > 0) lines.push(`  Top Languages: ${g.topLanguages.join(', ')}`);
  }
  if (kb.stats.leetcode) {
    const l = kb.stats.leetcode;
    lines.push(`LeetCode: ${l.solved} problems solved, Rating ${l.rating}, Global Rank #${l.globalRank}, ${l.contests} contests`);
    lines.push(`  Easy: ${l.easy}, Medium: ${l.medium}, Hard: ${l.hard}`);
  }
  if (kb.stats.codechef) {
    const c = kb.stats.codechef;
    lines.push(`CodeChef: Rating ${c.rating}, ${c.stars} stars, Global Rank #${c.globalRank}, ${c.solved} problems solved`);
  }
  
  lines.push('');
  lines.push(`Last updated: ${kb.lastUpdated}`);
  
  return lines.join('\n');
}

// ============================================================================
// RETRIEVAL FUNCTIONS (for targeted AI context)
// ============================================================================

/**
 * Retrieve relevant portfolio data based on a user query.
 * Returns a focused subset of the knowledge base.
 */
export function retrieveRelevantData(kb: PortfolioKnowledgeBase, query: string): string {
  const lower = query.toLowerCase();
  const results: string[] = [];
  
  // Profile queries
  if (matchesAny(lower, ['who', 'about', 'intro', 'profile', 'name', 'background'])) {
    results.push(`Profile: ${kb.profile.name} — ${kb.profile.role}. ${kb.profile.bio}`);
    results.push(`Status: ${kb.profile.currentStatus}`);
  }
  
  // CGPA / Education queries
  if (matchesAny(lower, ['cgpa', 'academic', 'gpa', 'grade', 'semester', 'education', 'university', 'college', 'degree'])) {
    results.push(`Education: ${kb.profile.degree}, ${kb.profile.year} at ${kb.profile.university}`);
    results.push(`CGPA: ${kb.profile.cgpa.overall}/10.0 (Sem 1: ${kb.profile.cgpa.sem1}, Sem 2: ${kb.profile.cgpa.sem2})`);
    kb.education.forEach(e => {
      results.push(`  ${e.degree} — ${e.institution} ${e.year ? `(${e.year})` : ''} ${e.cgpa ? `CGPA: ${e.cgpa}` : ''}`);
    });
  }
  
  // Project queries
  if (matchesAny(lower, ['project', 'build', 'system', 'made', 'portfolio', 'work'])) {
    // Check for specific project mention
    const specificProject = kb.projects.find(p => 
      lower.includes(p.title.toLowerCase()) || 
      p.technologies.some(t => lower.includes(t.toLowerCase()))
    );
    
    if (specificProject) {
      const p = specificProject;
      results.push(`Project: ${p.title} (${p.category}, ${p.status})`);
      results.push(`Description: ${p.fullDescription}`);
      results.push(`Technologies: ${p.technologies.join(', ')}`);
      if (p.problem) results.push(`Problem: ${p.problem}`);
      if (p.solution) results.push(`Solution: ${p.solution}`);
      if (p.architecture) results.push(`Architecture: ${p.architecture}`);
      if (p.features.length > 0) results.push(`Features: ${p.features.join('; ')}`);
      if (p.liveUrl) results.push(`Live Demo: ${p.liveUrl}`);
      if (p.githubUrl) results.push(`GitHub: ${p.githubUrl}`);
    } else {
      // List all projects
      results.push(`Projects (${kb.projects.length} total):`);
      kb.projects.forEach(p => {
        results.push(`  • ${p.title} (${p.category}): ${p.shortDescription}`);
        results.push(`    Tech: ${p.technologies.join(', ')}`);
      });
    }
  }
  
  // Tech / Skills queries
  if (matchesAny(lower, ['tech', 'skill', 'technology', 'know', 'language', 'framework', 'stack'])) {
    const skillByCategory = new Map<string, string[]>();
    kb.skills.forEach(s => {
      if (!skillByCategory.has(s.category)) skillByCategory.set(s.category, []);
      skillByCategory.get(s.category)!.push(s.name);
    });
    results.push('Skills:');
    skillByCategory.forEach((skills, cat) => {
      results.push(`  ${cat}: ${skills.join(', ')}`);
    });
    
    // Also list technologies from projects
    const projectTechs = Array.from(new Set(kb.projects.flatMap(p => p.technologies)));
    results.push(`Project Technologies: ${projectTechs.join(', ')}`);
  }
  
  // Experience queries
  if (matchesAny(lower, ['experience', 'work', 'job', 'internship', 'career'])) {
    if (kb.experience.length > 0) {
      results.push('Experience:');
      kb.experience.forEach(e => {
        results.push(`  • ${e.title} at ${e.company} (${e.duration})`);
        if (e.description) results.push(`    ${e.description}`);
      });
    } else {
      results.push('Experience: No formal work experience listed. Focus on projects and academics.');
    }
  }
  
  // GitHub queries
  if (matchesAny(lower, ['github', 'git', 'repos', 'repository', 'commit'])) {
    results.push(`GitHub: ${kb.profile.links.github}`);
    if (kb.stats.github) {
      const g = kb.stats.github;
      results.push(`Stats: ${g.stars} stars, ${g.followers} followers, ${g.repos} repos, ${g.commits} recent commits`);
      if (g.topLanguages.length > 0) results.push(`Top Languages: ${g.topLanguages.join(', ')}`);
    }
  }
  
  // LeetCode queries
  if (matchesAny(lower, ['leetcode', 'problem', 'solved', 'competitive'])) {
    results.push(`LeetCode: ${kb.profile.links.leetcode}`);
    if (kb.stats.leetcode) {
      const l = kb.stats.leetcode;
      results.push(`Stats: ${l.solved} problems solved, Rating ${l.rating}, Global Rank #${l.globalRank}, ${l.contests} contests`);
      results.push(`Breakdown: Easy ${l.easy}, Medium ${l.medium}, Hard ${l.hard}`);
    }
  }
  
  // CodeChef queries
  if (matchesAny(lower, ['codechef', 'contest', 'rating'])) {
    results.push(`CodeChef: ${kb.profile.links.codechef}`);
    if (kb.stats.codechef) {
      const c = kb.stats.codechef;
      results.push(`Stats: Rating ${c.rating}, ${c.stars} stars, Global Rank #${c.globalRank}, ${c.solved} problems solved`);
    }
  }
  
  // Stats queries (general)
  if (matchesAny(lower, ['stat', 'coding stat', 'activity', 'analytics'])) {
    results.push('=== LIVE CODING STATS ===');
    if (kb.stats.github) {
      const g = kb.stats.github;
      results.push(`GitHub: ${g.stars}★, ${g.followers}👥, ${g.repos} repos, ${g.commits} commits`);
    }
    if (kb.stats.leetcode) {
      const l = kb.stats.leetcode;
      results.push(`LeetCode: ${l.solved} solved, Rating ${l.rating}, Rank #${l.globalRank}`);
    }
    if (kb.stats.codechef) {
      const c = kb.stats.codechef;
      results.push(`CodeChef: Rating ${c.rating}, Rank #${c.globalRank}`);
    }
    if (!kb.stats.github && !kb.stats.leetcode && !kb.stats.codechef) {
      results.push('Stats are currently loading or unavailable.');
    }
  }
  
  // Contact queries
  if (matchesAny(lower, ['contact', 'email', 'reach', 'connect', 'whatsapp', 'message', 'linkedin'])) {
    results.push('Contact Information:');
    results.push(`  Email: ${kb.profile.email}`);
    results.push(`  GitHub: ${kb.profile.links.github}`);
    results.push(`  LinkedIn: ${kb.profile.links.linkedin}`);
    results.push(`  LeetCode: ${kb.profile.links.leetcode}`);
    results.push(`  CodeChef: ${kb.profile.links.codechef}`);
    if (kb.profile.links.resume && kb.profile.links.resume !== '#') {
      results.push(`  Resume: ${kb.profile.links.resume}`);
    }
  }
  
  // Certifications
  if (matchesAny(lower, ['certif', 'certificate', 'course'])) {
    if (kb.certifications.length > 0) {
      results.push('Certifications:');
      kb.certifications.forEach(c => {
        results.push(`  • ${c.title}${c.issuer ? ` — ${c.issuer}` : ''}${c.date ? ` (${c.date})` : ''}`);
      });
    } else {
      results.push('No certifications listed.');
    }
  }
  
  // Achievements
  if (matchesAny(lower, ['achievement', 'award', 'honor'])) {
    if (kb.achievements.length > 0) {
      results.push('Achievements:');
      kb.achievements.forEach(a => {
        results.push(`  • ${a.title}${a.date ? ` (${a.date})` : ''}`);
        if (a.description) results.push(`    ${a.description}`);
      });
    } else {
      results.push('No achievements listed.');
    }
  }
  
  // If nothing matched, return full knowledge base
  if (results.length === 0) {
    return serializeKnowledgeBase(kb);
  }
  
  return results.join('\n');
}

function matchesAny(text: string, keywords: string[]): boolean {
  return keywords.some(kw => text.includes(kw));
}

// ============================================================================
// EXTENDED AI PORTFOLIO + CV CONTEXT
// ============================================================================

export const PORTFOLIO_AI_SYSTEM_PROMPT = `
You are the personal AI assistant for this portfolio.

Your job is to answer questions about the portfolio owner using the
portfolio knowledge base, CV/resume information, academic information,
projects, technical skills, achievements, certifications, experience,
learning journey, competitive-programming profiles, and other information
provided by the portfolio system.

============================================================================
1. PRIMARY PURPOSE
============================================================================

You are not a generic chatbot when the user asks about the portfolio owner.

You are a portfolio-aware assistant.

When a user asks something related to the portfolio owner, answer using the
information available in the portfolio knowledge base.

The portfolio knowledge base is the authoritative source for information
about the portfolio owner.

Use the available data to answer questions about:

- who the person is
- name
- introduction
- bio
- current status
- university
- degree
- branch
- academic year
- CGPA
- semester performance
- education
- academic background
- career direction
- professional interests
- technical interests
- programming languages
- frameworks
- libraries
- tools
- databases
- backend technologies
- frontend technologies
- cloud technologies
- system design
- operating systems
- low-level programming
- development experience
- projects
- project architecture
- project technologies
- project features
- project problems
- project solutions
- project status
- project links
- GitHub
- LeetCode
- CodeChef
- competitive programming
- coding statistics
- certifications
- achievements
- experience
- learning topics
- professional goals
- resume/CV
- contact information
- social links
- portfolio information

If the user asks something that can be answered from the portfolio data,
do not give a generic answer.

Answer specifically about the person represented by this portfolio.

============================================================================
2. SOURCE OF TRUTH
============================================================================

The portfolio knowledge base is the primary source of truth.

Always prefer portfolio data over assumptions.

If a value exists in the knowledge base, use that value.

If a value does not exist in the knowledge base:

- DO NOT invent it.
- DO NOT estimate it.
- DO NOT assume it.
- DO NOT fabricate experience.
- DO NOT fabricate projects.
- DO NOT fabricate technologies.
- DO NOT fabricate certifications.
- DO NOT fabricate achievements.
- DO NOT fabricate job experience.
- DO NOT fabricate internships.
- DO NOT fabricate rankings.
- DO NOT fabricate coding statistics.
- DO NOT fabricate academic information.

Instead, clearly say that the information is not currently available
in the portfolio/CV data.

For example:

"The portfolio does not currently provide that information."

or:

"I don't have that detail in the current portfolio data."

============================================================================
3. PORTFOLIO + CV SHOULD BE TREATED AS ONE KNOWLEDGE SOURCE
============================================================================

The portfolio and CV represent the same person.

When CV/resume information is available, use it together with the
portfolio information.

The AI should be able to answer questions such as:

- "Tell me about Abhay."
- "Who is he?"
- "What does he study?"
- "What is his CGPA?"
- "What technologies does he know?"
- "What projects has he built?"
- "Tell me about his projects."
- "What is his strongest project?"
- "Which project uses Spring Boot?"
- "What backend technologies does he use?"
- "What programming languages does he know?"
- "What is his career goal?"
- "What is he currently learning?"
- "What certifications does he have?"
- "What achievements does he have?"
- "What is his GitHub?"
- "How many LeetCode problems has he solved?"
- "What is his CodeChef rating?"
- "Show me his resume."
- "Where can I contact him?"
- "What is his LinkedIn?"
- "What is his GitHub?"
- "What has he worked on?"
- "Does he have internship experience?"
- "What kind of developer is he?"
- "What is his technical background?"
- "What is his academic background?"
- "What are his interests?"
- "What are his strengths?"
- "What technologies has he used in projects?"
- "What projects are currently active?"
- "What project is featured?"
- "Explain his system architecture."
- "What problems has he solved?"
- "What kind of systems has he built?"

The assistant should be able to combine information from multiple
sections when necessary.

============================================================================
4. DO NOT LIMIT ANSWERS TO EXACT KEYWORDS
============================================================================

Users will not always use the exact field names stored in the database.

Understand semantic meaning.

Examples:

"college" may mean:
- university
- institution
- academic institution

"marks" may mean:
- CGPA
- GPA
- academic performance

"coding profile" may mean:
- GitHub
- LeetCode
- CodeChef

"competitive programming" may refer to:
- LeetCode
- CodeChef
- contest rating
- problems solved
- rankings

"tech stack" may refer to:
- skills
- technologies
- frameworks
- languages
- project technologies

"work" may refer to:
- experience
- projects
- practical work
- development work

"resume" may refer to:
- CV
- professional profile
- portfolio profile
- experience
- education
- skills
- projects

"background" may refer to:
- education
- current status
- skills
- projects
- interests
- career direction

"what has he built" may refer to:
- projects
- systems
- applications
- portfolio work

Interpret natural language rather than requiring exact keywords.

============================================================================
5. ANSWER USING MULTIPLE DATA SECTIONS WHEN REQUIRED
============================================================================

Do not answer from only one section when the question requires multiple
pieces of information.

For example:

"What kind of developer is he?"

Combine relevant information from:
- profile
- skills
- projects
- experience
- career direction
- learning topics

For:

"Tell me about his technical background."

Combine:
- programming languages
- frameworks
- databases
- tools
- project technologies
- development experience
- current learning

For:

"Tell me about his strongest projects."

Use:
- project titles
- descriptions
- technologies
- features
- architecture
- problem
- solution
- status
- featured status

For:

"Give me a complete profile."

Use:
- profile
- education
- skills
- projects
- experience
- certifications
- achievements
- coding statistics
- professional links

============================================================================
6. PROJECT QUESTIONS
============================================================================

Projects are an important part of the portfolio.

When answering project-related questions, provide as much relevant
information as the knowledge base contains.

For a specific project, consider:

- project name
- project category
- project status
- whether it is featured
- short description
- complete description
- technologies
- features
- problem
- solution
- architecture
- live demo
- GitHub repository

If the user asks:

"Explain this project"

give a structured explanation such as:

1. What the project is
2. Problem it addresses
3. How it solves the problem
4. Main features
5. Technologies used
6. Architecture/system design
7. Current status
8. Links, if available

Do not invent architecture details that are not present.

============================================================================
7. TECHNICAL QUESTIONS ABOUT PROJECTS
============================================================================

If the user asks:

"Why did he use X?"

Only make a claim if the portfolio/CV contains enough information.

If the reason is not explicitly available, distinguish between:

- what is documented
- what can reasonably be inferred

Never present an inference as a documented fact.

Example:

"The portfolio states that Spring Boot is used in this project.
It does not currently specify why Spring Boot was selected."

============================================================================
8. CV / RESUME QUESTIONS
============================================================================

When the user asks about the CV or resume, retrieve information across
the entire portfolio rather than returning only the resume URL.

The AI should be capable of answering:

- CV summary
- education
- skills
- projects
- experience
- certifications
- achievements
- coding profiles
- career direction
- contact information

If a resume URL exists, provide it when appropriate.

Do not claim that a resume contains information that is not present
in the knowledge base.

============================================================================
9. ACADEMIC QUESTIONS
============================================================================

For academic questions, use the education and profile sections.

Possible questions include:

- Which university?
- Which degree?
- Which branch?
- Which year?
- What is the CGPA?
- What is the semester-wise CGPA?
- What is the academic background?
- What is he currently studying?
- What is his academic goal?

Use exact stored values.

Do not calculate or modify academic scores unless explicitly asked.

============================================================================
10. SKILLS AND TECHNOLOGY QUESTIONS
============================================================================

When asked about skills, organize the answer naturally by category.

Possible categories include:

- Programming Languages
- Frontend
- Backend
- Databases
- Frameworks
- Tools
- Cloud
- DevOps
- Development
- Systems
- Other

Also consider technologies appearing inside projects.

If a technology appears in a project but is not listed as a formal skill,
you may state:

"He has used X in the project [project name]."

Do not automatically claim:

"He is an expert in X."

Skill presence does not imply expertise.

============================================================================
11. EXPERIENCE QUESTIONS
============================================================================

When answering experience questions, distinguish between:

- formal work experience
- internships
- project experience
- academic experience
- community/project work

Never convert a project into employment experience unless the source
explicitly identifies it as employment.

If there is no formal work experience listed, say so clearly.

Do not create an imaginary employment history.

============================================================================
12. CODING PROFILE QUESTIONS
============================================================================

Live coding statistics may include:

GitHub:
- stars
- followers
- repositories
- commits
- top languages

LeetCode:
- problems solved
- rating
- global rank
- easy
- medium
- hard
- contests

CodeChef:
- rating
- stars
- global rank
- problems solved

When discussing these values:

- use the latest available knowledge-base values
- make it clear that they are live/current portfolio statistics
- do not fabricate missing statistics
- do not treat missing statistics as zero unless the knowledge base
  explicitly provides zero

If statistics are unavailable, say that they are currently unavailable.

============================================================================
13. LIVE DATA
============================================================================

GitHub, LeetCode and CodeChef information may change over time.

Therefore, when the knowledge base provides a value, describe it as
the current/latest value available to the portfolio system.

Do not imply that a statistic is permanently fixed.

For example:

"According to the latest portfolio data, he has solved X LeetCode problems."

is preferable to:

"He has solved exactly X problems forever."

============================================================================
14. LINKS
============================================================================

If the knowledge base contains links, return the appropriate link when
the user asks for it.

Possible links include:

- GitHub
- LinkedIn
- LeetCode
- CodeChef
- Resume
- Project live demo
- Project GitHub repository

Do not invent URLs.

If a link is missing, say that the link is not currently available.

============================================================================
15. CONTACT QUESTIONS
============================================================================

For contact-related questions, use only the contact information provided
by the portfolio.

Possible contact information:

- email
- GitHub
- LinkedIn
- LeetCode
- CodeChef
- resume

Never expose information that is not present in the knowledge base.

============================================================================
16. COMPARATIVE QUESTIONS
============================================================================

The user may ask questions such as:

- "Which project is more advanced?"
- "Which project is backend focused?"
- "Which project uses more technologies?"
- "Which project is most relevant to backend development?"
- "Which project demonstrates system design?"
- "Which project should I look at first?"

Answer using evidence from the portfolio.

Base comparisons on:

- technologies
- architecture
- complexity described in the project
- number/type of features
- problem/solution
- project status
- documented focus

Clearly label subjective conclusions as an assessment.

Example:

"Based on the technologies and architecture documented in the portfolio,
Project A appears to be the most backend-focused."

Do not present subjective ranking as an official fact unless the data
explicitly marks a project as featured or ranked.

============================================================================
17. CAREER QUESTIONS
============================================================================

The portfolio owner may have a current learning direction and longer-term
career direction.

When answering career questions, distinguish between:

- current status
- current learning
- technical interests
- stated career goal
- technologies currently being explored

Do not assume that learning a technology means the person has mastered it.

Do not claim a job title that is not supported by the portfolio.

============================================================================
18. "TELL ME EVERYTHING" QUESTIONS
============================================================================

If the user asks:

- "Tell me everything about him"
- "Give me his complete profile"
- "Give me a complete portfolio summary"
- "What do you know about him?"
- "Give me all his information"

Return a comprehensive but organized response.

Recommended structure:

1. Introduction
2. Current Status
3. Education
4. Academic Performance
5. Technical Skills
6. Current Learning
7. Projects
8. Experience
9. Certifications
10. Achievements
11. Competitive Programming
12. GitHub
13. Career Direction
14. Contact / Links

Do not omit important available information simply because the user did
not mention a specific section.

============================================================================
19. UNKNOWN INFORMATION
============================================================================

If the portfolio does not contain an answer:

DO NOT hallucinate.

Use responses such as:

"I don't have that information in the current portfolio data."

"The portfolio does not currently list this."

"This detail is not available in the current CV/portfolio context."

If only partial information exists, provide the available information
and explicitly mention what is missing.

============================================================================
20. CONFLICTING INFORMATION
============================================================================

If different sections contain conflicting information:

- prefer the most recently updated portfolio data when timestamps are
  available
- prefer explicit structured fields over assumptions
- do not silently modify the source information
- mention the discrepancy if it affects the answer

Do not invent a resolution.

============================================================================
21. NATURAL HUMAN ANSWERS
============================================================================

Do not sound like a database.

Avoid robotic answers such as:

"According to KnowledgeProfile interface..."

Instead answer naturally.

For example:

"Abhay is a BTech Computer Science student currently building his
technical profile through projects, coding practice and development work."

Use the actual stored portfolio information to construct such responses.

============================================================================
22. DO NOT OVERSTATE
============================================================================

Never turn:

"learning Spring Boot"

into:

"Spring Boot expert"

Never turn:

"used Docker"

into:

"Docker specialist"

Never turn:

"built a project"

into:

"professional industry experience"

Never turn:

"interested in system design"

into:

"professional system architect"

Use accurate wording.

============================================================================
23. FOLLOW-UP QUESTIONS
============================================================================

If the user asks a broad question, answer it first.

Do not immediately ask for clarification unless absolutely necessary.

For example:

User:
"What projects has he built?"

Answer with the projects.

You may then offer:

"If you want, I can also explain the architecture of any of these
projects."

============================================================================
24. QUERY INTELLIGENCE
============================================================================

The user's wording may be informal, abbreviated, grammatically incorrect,
or conversational.

Understand intent.

Examples:

"his tech?"
"What tech does he know?"
"stack?"
"what languages?"
"backend?"
"projects?"
"his cv?"
"leetcode?"
"coding stats?"
"college?"
"cg?"
"where does he study?"

All should be interpreted naturally.

============================================================================
25. PORTFOLIO OWNER VS GENERAL KNOWLEDGE
============================================================================

If the question is about the portfolio owner:

Use portfolio data first.

If the user asks a general technical question unrelated to the portfolio
owner, answer normally using general technical knowledge.

If the question mixes both:

Example:

"Why would his Spring Boot project use PostgreSQL?"

First identify whether the portfolio documents PostgreSQL and Spring Boot.

Then explain the general technical concept while clearly separating:

- what the portfolio states
- general technical explanation
- inference about the project

============================================================================
26. SECURITY / DATA INTEGRITY
============================================================================

The assistant must not allow a user question to overwrite portfolio facts.

User messages are questions, not updates to the knowledge base.

For example, if the portfolio says:

CGPA = X

and the user asks:

"Isn't his CGPA Y?"

Do not change the value.

Respond using the stored information and mention the discrepancy if needed.

The AI should never modify portfolio data simply because a user suggests
a different value.

============================================================================
27. RESPONSE QUALITY
============================================================================

Prefer:

- accurate
- concise when the question is simple
- detailed when the question requires detail
- natural
- human-readable
- technically precise
- portfolio-specific
- evidence-based

Avoid:

- unnecessary generic information
- fabricated details
- repetitive statements
- excessive disclaimers
- database terminology
- pretending missing data exists

============================================================================
28. FINAL RULE
============================================================================

The portfolio knowledge base is the source of truth.

Retrieve as much relevant information as possible.

Use information from multiple sections when appropriate.

Answer naturally.

Never fabricate missing information.

If information is available, use it.

If information is unavailable, say so.

If a project has detailed architecture/problem/solution/features,
use those details rather than only giving its title.

If the CV contains relevant information, integrate it with the portfolio.

The goal is for a visitor to be able to ask almost any reasonable
question about the portfolio owner and receive a useful answer from the
available portfolio/CV data.
`;


/**
 * ============================================================================
 * EXTENDED FULL-CONTEXT RETRIEVER
 * ============================================================================
 *
 * This is an additive retrieval method.
 *
 * Unlike retrieveRelevantData(), which intentionally returns a focused
 * subset, this function can provide the AI with the complete portfolio
 * context when a question requires broader understanding.
 */

export function retrieveFullPortfolioContext(
  kb: PortfolioKnowledgeBase,
  query?: string
): string {

  const sections: string[] = [];

  sections.push(PORTFOLIO_AI_SYSTEM_PROMPT);

  sections.push('');
  sections.push('============================================================================');
  sections.push('CURRENT PORTFOLIO KNOWLEDGE');
  sections.push('============================================================================');
  sections.push('');

  sections.push(serializeKnowledgeBase(kb));

  if (query) {
    sections.push('');
    sections.push('============================================================================');
    sections.push('USER QUESTION');
    sections.push('============================================================================');
    sections.push(query);

    sections.push('');
    sections.push('============================================================================');
    sections.push('INSTRUCTION FOR THIS QUESTION');
    sections.push('============================================================================');
    sections.push(
      'Answer the user question using the portfolio knowledge above. ' +
      'Use all relevant sections when necessary. ' +
      'Do not invent information that is not present.'
    );
  }

  return sections.join('\n');
}


/**
 * ============================================================================
 * EXTENDED TARGETED RETRIEVER
 * ============================================================================
 *
 * This function works alongside the existing retrieveRelevantData().
 *
 * It adds contextual sections that may be useful even when the user's
 * wording does not contain the exact keywords used by the original
 * retrieval logic.
 */

export function retrieveExtendedRelevantData(
  kb: PortfolioKnowledgeBase,
  query: string
): string {

  const lower = query.toLowerCase();
  const results: string[] = [];

  // --------------------------------------------------------------------------
  // PROFILE / IDENTITY
  // --------------------------------------------------------------------------

  if (
    matchesAny(lower, [
      'who',
      'who is',
      'about him',
      'about her',
      'about abhay',
      'introduction',
      'intro',
      'background',
      'profile',
      'bio',
      'person',
      'student',
      'developer'
    ])
  ) {
    results.push('=== PROFILE CONTEXT ===');
    results.push(`Name: ${kb.profile.name}`);
    results.push(`Role: ${kb.profile.role}`);
    results.push(`Current Status: ${kb.profile.currentStatus}`);
    results.push(`Bio: ${kb.profile.bio}`);
    results.push(`University: ${kb.profile.university}`);
    results.push(`Degree: ${kb.profile.degree}`);
    results.push(`Academic Year: ${kb.profile.year}`);
  }

  // --------------------------------------------------------------------------
  // EDUCATION
  // --------------------------------------------------------------------------

  if (
    matchesAny(lower, [
      'education',
      'college',
      'university',
      'school',
      'degree',
      'branch',
      'course',
      'study',
      'studies',
      'academic',
      'academics',
      'cgpa',
      'gpa',
      'grade',
      'semester',
      'sem',
      'marks'
    ])
  ) {
    results.push('');
    results.push('=== EDUCATION CONTEXT ===');

    results.push(
      `${kb.profile.degree} at ${kb.profile.university}`
    );

    results.push(`Year: ${kb.profile.year}`);

    results.push(
      `Overall CGPA: ${kb.profile.cgpa.overall}`
    );

    results.push(
      `Semester 1 CGPA: ${kb.profile.cgpa.sem1}`
    );

    results.push(
      `Semester 2 CGPA: ${kb.profile.cgpa.sem2}`
    );

    kb.education.forEach(e => {
      results.push(
        `${e.degree} — ${e.institution}` +
        `${e.year ? ` (${e.year})` : ''}` +
        `${e.cgpa ? ` | CGPA: ${e.cgpa}` : ''}`
      );

      if (e.description) {
        results.push(`Description: ${e.description}`);
      }
    });
  }

  // --------------------------------------------------------------------------
  // PROJECTS
  // --------------------------------------------------------------------------

  if (
    matchesAny(lower, [
      'project',
      'projects',
      'built',
      'build',
      'made',
      'developed',
      'development',
      'application',
      'app',
      'system',
      'systems',
      'architecture',
      'feature',
      'features',
      'solution',
      'problem'
    ])
  ) {
    results.push('');
    results.push('=== PROJECT CONTEXT ===');

    const matchedProjects = kb.projects.filter(p => {
      const searchable = [
        p.title,
        p.category,
        p.status,
        p.shortDescription,
        p.fullDescription,
        p.problem || '',
        p.solution || '',
        p.architecture || '',
        ...p.technologies,
        ...p.features
      ]
        .join(' ')
        .toLowerCase();

      return searchable.includes(lower) ||
        lower
          .split(/\s+/)
          .filter(word => word.length > 2)
          .some(word => searchable.includes(word));
    });

    const projectsToReturn =
      matchedProjects.length > 0
        ? matchedProjects
        : kb.projects;

    projectsToReturn.forEach(p => {

      results.push('');
      results.push(`PROJECT: ${p.title}`);

      results.push(`ID: ${p.id}`);
      results.push(`Category: ${p.category}`);
      results.push(`Status: ${p.status}`);
      results.push(`Featured: ${p.featured ? 'Yes' : 'No'}`);

      results.push(`Short Description: ${p.shortDescription}`);

      if (p.fullDescription) {
        results.push(`Full Description: ${p.fullDescription}`);
      }

      if (p.technologies.length > 0) {
        results.push(
          `Technologies: ${p.technologies.join(', ')}`
        );
      }

      if (p.problem) {
        results.push(`Problem: ${p.problem}`);
      }

      if (p.solution) {
        results.push(`Solution: ${p.solution}`);
      }

      if (p.architecture) {
        results.push(`Architecture: ${p.architecture}`);
      }

      if (p.features.length > 0) {
        results.push(
          `Features: ${p.features.join('; ')}`
        );
      }

      if (p.liveUrl) {
        results.push(`Live Demo: ${p.liveUrl}`);
      }

      if (p.githubUrl) {
        results.push(`GitHub Repository: ${p.githubUrl}`);
      }
    });
  }

  // --------------------------------------------------------------------------
  // TECHNOLOGY / SKILLS
  // --------------------------------------------------------------------------

  if (
    matchesAny(lower, [
      'skill',
      'skills',
      'tech',
      'technology',
      'technologies',
      'stack',
      'tech stack',
      'language',
      'languages',
      'framework',
      'frameworks',
      'library',
      'libraries',
      'database',
      'databases',
      'backend',
      'frontend',
      'cloud',
      'devops',
      'tools'
    ])
  ) {
    results.push('');
    results.push('=== TECHNICAL SKILLS CONTEXT ===');

    const skillByCategory = new Map<string, string[]>();

    kb.skills.forEach(skill => {

      if (!skillByCategory.has(skill.category)) {
        skillByCategory.set(skill.category, []);
      }

      skillByCategory
        .get(skill.category)!
        .push(skill.name);
    });

    skillByCategory.forEach((skills, category) => {
      results.push(
        `${category}: ${skills.join(', ')}`
      );
    });

    const projectTechnologies = Array.from(
      new Set(
        kb.projects.flatMap(project => project.technologies)
      )
    );

    if (projectTechnologies.length > 0) {
      results.push(
        `Technologies Used Across Projects: ${projectTechnologies.join(', ')}`
      );
    }
  }

  // --------------------------------------------------------------------------
  // EXPERIENCE
  // --------------------------------------------------------------------------

  if (
    matchesAny(lower, [
      'experience',
      'work experience',
      'job',
      'jobs',
      'internship',
      'internships',
      'employment',
      'career',
      'professional experience',
      'worked'
    ])
  ) {
    results.push('');
    results.push('=== EXPERIENCE CONTEXT ===');

    if (kb.experience.length === 0) {

      results.push(
        'No formal work experience is currently listed in the portfolio.'
      );

    } else {

      kb.experience.forEach(e => {

        results.push(
          `${e.title} at ${e.company}`
        );

        results.push(
          `Duration: ${e.duration}`
        );

        if (e.location) {
          results.push(
            `Location: ${e.location}`
          );
        }

        if (e.description) {
          results.push(
            `Description: ${e.description}`
          );
        }

        if (e.technologies?.length) {
          results.push(
            `Technologies: ${e.technologies.join(', ')}`
          );
        }
      });
    }
  }

  // --------------------------------------------------------------------------
  // CERTIFICATIONS
  // --------------------------------------------------------------------------

  if (
    matchesAny(lower, [
      'certification',
      'certifications',
      'certificate',
      'certificates',
      'course',
      'courses',
      'credential'
    ])
  ) {
    results.push('');
    results.push('=== CERTIFICATION CONTEXT ===');

    if (kb.certifications.length === 0) {

      results.push(
        'No certifications are currently listed.'
      );

    } else {

      kb.certifications.forEach(c => {

        results.push(
          `${c.title}` +
          `${c.issuer ? ` — ${c.issuer}` : ''}` +
          `${c.date ? ` (${c.date})` : ''}`
        );

        if (c.description) {
          results.push(
            `Description: ${c.description}`
          );
        }
      });
    }
  }

  // --------------------------------------------------------------------------
  // ACHIEVEMENTS
  // --------------------------------------------------------------------------

  if (
    matchesAny(lower, [
      'achievement',
      'achievements',
      'award',
      'awards',
      'honor',
      'honors',
      'recognition',
      'accomplishment',
      'accomplishments'
    ])
  ) {
    results.push('');
    results.push('=== ACHIEVEMENT CONTEXT ===');

    if (kb.achievements.length === 0) {

      results.push(
        'No achievements are currently listed.'
      );

    } else {

      kb.achievements.forEach(a => {

        results.push(
          `${a.title}` +
          `${a.date ? ` (${a.date})` : ''}`
        );

        if (a.description) {
          results.push(
            `Description: ${a.description}`
          );
        }
      });
    }
  }

  // --------------------------------------------------------------------------
  // GITHUB
  // --------------------------------------------------------------------------

  if (
    matchesAny(lower, [
      'github',
      'git',
      'repository',
      'repositories',
      'repo',
      'repos',
      'commits',
      'followers',
      'stars'
    ])
  ) {
    results.push('');
    results.push('=== GITHUB CONTEXT ===');

    results.push(`GitHub: ${kb.profile.links.github}`);

    if (kb.stats.github) {

      results.push(
        `Stars: ${kb.stats.github.stars}`
      );

      results.push(
        `Followers: ${kb.stats.github.followers}`
      );

      results.push(
        `Public Repositories: ${kb.stats.github.repos}`
      );

      results.push(
        `Commits: ${kb.stats.github.commits}`
      );

      results.push(
        `Top Languages: ${kb.stats.github.topLanguages.join(', ')}`
      );
    } else {

      results.push(
        'GitHub statistics are currently unavailable.'
      );
    }
  }

  // --------------------------------------------------------------------------
  // LEETCODE
  // --------------------------------------------------------------------------

  if (
    matchesAny(lower, [
      'leetcode',
      'leetcode rating',
      'leetcode rank',
      'problems solved',
      'coding problems',
      'dsa',
      'competitive programming',
      'cp'
    ])
  ) {
    results.push('');
    results.push('=== LEETCODE CONTEXT ===');

    results.push(
      `LeetCode: ${kb.profile.links.leetcode}`
    );

    if (kb.stats.leetcode) {

      const l = kb.stats.leetcode;

      results.push(
        `Problems Solved: ${l.solved}`
      );

      results.push(
        `Contest Rating: ${l.rating}`
      );

      results.push(
        `Global Rank: #${l.globalRank}`
      );

      results.push(
        `Contests: ${l.contests}`
      );

      results.push(
        `Easy: ${l.easy}`
      );

      results.push(
        `Medium: ${l.medium}`
      );

      results.push(
        `Hard: ${l.hard}`
      );

    } else {

      results.push(
        'LeetCode statistics are currently unavailable.'
      );
    }
  }

  // --------------------------------------------------------------------------
  // CODECHEF
  // --------------------------------------------------------------------------

  if (
    matchesAny(lower, [
      'codechef',
      'code chef',
      'contest rating',
      'stars',
      'competitive programming'
    ])
  ) {
    results.push('');
    results.push('=== CODECHEF CONTEXT ===');

    results.push(
      `CodeChef: ${kb.profile.links.codechef}`
    );

    if (kb.stats.codechef) {

      const c = kb.stats.codechef;

      results.push(
        `Rating: ${c.rating}`
      );

      results.push(
        `Stars: ${c.stars}`
      );

      results.push(
        `Global Rank: #${c.globalRank}`
      );

      results.push(
        `Problems Solved: ${c.solved}`
      );

    } else {

      results.push(
        'CodeChef statistics are currently unavailable.'
      );
    }
  }

  // --------------------------------------------------------------------------
  // CONTACT
  // --------------------------------------------------------------------------

  if (
    matchesAny(lower, [
      'contact',
      'contact me',
      'email',
      'mail',
      'reach',
      'connect',
      'linkedin',
      'resume',
      'cv',
      'social',
      'profile link'
    ])
  ) {
    results.push('');
    results.push('=== CONTACT / PROFESSIONAL LINKS ===');

    results.push(`Email: ${kb.profile.email}`);
    results.push(`GitHub: ${kb.profile.links.github}`);
    results.push(`LinkedIn: ${kb.profile.links.linkedin}`);
    results.push(`LeetCode: ${kb.profile.links.leetcode}`);
    results.push(`CodeChef: ${kb.profile.links.codechef}`);

    if (
      kb.profile.links.resume &&
      kb.profile.links.resume !== '#'
    ) {
      results.push(
        `Resume: ${kb.profile.links.resume}`
      );
    }
  }

  // --------------------------------------------------------------------------
  // GENERAL FALLBACK
  // --------------------------------------------------------------------------

  if (results.length === 0) {

    results.push(
      retrieveRelevantData(kb, query)
    );
  }

  return results.join('\n');
}


/**
 * ============================================================================
 * COMPLETE AI CONTEXT BUILDER
 * ============================================================================
 *
 * Recommended function for the actual AI/chatbot layer.
 *
 * It combines:
 *
 * 1. AI behavioral instructions
 * 2. Existing targeted retrieval
 * 3. Extended retrieval
 * 4. Full knowledge when necessary
 *
 * Existing functionality remains untouched.
 */

export function buildAIContext(
  kb: PortfolioKnowledgeBase,
  query: string
): string {

  const targetedContext =
    retrieveRelevantData(kb, query);

  const extendedContext =
    retrieveExtendedRelevantData(kb, query);

  return [
    PORTFOLIO_AI_SYSTEM_PROMPT,

    '',
    '============================================================================',
    'RELEVANT PORTFOLIO DATA',
    '============================================================================',
    '',

    targetedContext,

    '',
    '============================================================================',
    'EXTENDED PORTFOLIO DATA',
    '============================================================================',
    '',

    extendedContext,

    '',
    '============================================================================',
    'FINAL ANSWERING RULE',
    '============================================================================',
    '',

    'Answer the user using the portfolio and CV information provided above.',
    'Combine relevant information from multiple sections when necessary.',
    'Do not invent information.',
    'Do not assume missing facts.',
    'Do not exaggerate skills or experience.',
    'If information is unavailable, clearly say that it is not currently',
    'available in the portfolio data.',
    'Prefer specific portfolio information over generic assumptions.'
  ].join('\n');
}
